### ISSUE TITLE
Getting "The remote server returned an error: (403) Forbidden."

### ISSUE THREAD

**Issue by basutirtha** [DataThirstLtd/databricks.vsts.tools#26]
Hi,

I am using Databricks DBFS File Deployment task to deploy files, even after providing the correct token, we are getting the below error.
It is working in another project where the same task is being used.

2020-07-20T17:41:10.8141432Z ##[debug]Error 403 Invalid access token.
2020-07-20T17:41:10.8161869Z ##[debug]
2020-07-20T17:41:10.8180588Z ##[debug]HTTP ERROR 403
2020-07-20T17:41:10.8199301Z ##[debug]Problem accessing /api/2.0/dbfs/put. Reason:
2020-07-20T17:41:10.8217848Z ##[debug]    Invalid access token.
.......
…..
2020-07-20T17:41:10.8750629Z ##[debug]System.Net.WebException: The remote server returned an error: (403) Forbidden.
2020-07-20T17:41:10.8787047Z ##[debug]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
2020-07-20T17:41:10.8797838Z ##[debug]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
2020-07-20T17:41:10.9139033Z ##[error]The remote server returned an error: (403) Forbidden.
2020-07-20T17:41:10.9158189Z ##[debug]Processed: ##vso[task.logissue type=error]The remote server returned an error: (403) Forbidden.
2020-07-20T17:41:10.9179681Z ##[debug]Processed: ##vso[task.complete result=Failed]
2020-07-20T17:41:10.9695409Z ##[section]Finishing: Databricks DBFS File Deployment

**Comment by simondmorias** [comment]
Honestly the token is wrong/expired or the region is incorrect.

To test it use PowerShell on your local machine and run this:
```
$Token = "dapi1234567890"
$Region = "westeurope"
Install-Module -Name azure.databricks.cicd.tools -Scope CurrentUser
Import-Module -Name azure.databricks.cicd.tools
Get-DatabricksClusters -BearerToken $Token -Region $Region
```

**Comment by basutirtha** [comment]
that worked. thank you.
